version: "3"

services:
  redis:
    image: redis
    container_name: redis
    networks:
      - chat-network

  db:
    image: postgres:14
    container_name: postgres
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - chat-network

  web:
    build: .
    container_name: messaging-app
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=messaging_app.settings
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
    depends_on:
      - redis
      - db
    networks:
      - chat-network

volumes:
  postgres_data:

networks:
  chat-network:
    driver: bridge